### ISSUE TITLE
Add hover state to reticle

### ISSUE THREAD

**Issue by FreakTheMighty** [htmlfusion/holo-ui#5]
We're going to test a few different designs for selecting and activating items. Our current version displays information after pointing at an item for a small amount of time. This version will display a "focus" state, then allow the user to "click" the item.

**Comment by FreakTheMighty** [comment]
@rafai check this out.

**Comment by rafai** [comment]
Cool I will check it

**Comment by rafai** [comment]
Test to see if htmlfusion org is saved to my profile upon entering this comment.

**Comment by FreakTheMighty** [comment]
Check out these mock ups.
[ROUND_UI.pdf](https://github.com/htmlfusion/holo-ui/files/1154/ROUND_UI.pdf)

**Comment by FreakTheMighty** [comment]
I've implemented the onFocus state for the retical. I've also made it so that the retical moves to the depth of the object that the user is focused on. The pull request is here #7

**Comment by FreakTheMighty** [comment]
@rafai This is ready for review.

**Comment by FreakTheMighty** [comment]
@pedro, what do you think about having the on hover state of the reticle be something like a magnifying glass? When the user hovers over an object, the reticle could expand, like it currently does, but additionally, the user could see through the reticle. This would allow the user to get a preview.

**Comment by poplockanddrop** [comment]
hmmm im not sure. Sounds like a cool idea but if the preview is out text I have a feeling it would be hard to make out. Either way lets try it and see what it looks like.

**Comment by FreakTheMighty** [comment]
I recorded two demo videos last night. I'm going to work on a blog post and video for those demos. I think we can consider this ready for review. @rafai @poplockanddrop wanna take a look?
