### ISSUE TITLE
Testing Procedure

### ISSUE THREAD

**Issue by rafai** [htmlfusion/holo-ui#6]
This ticket is for setting up the user testing procedure:
Scenarios, questions and feedback.

**Comment by FreakTheMighty** [comment]
@rafai can you upload what you wrote up last night? I'd like to contribute to it.

**Comment by rafai** [comment]
Overarching HOLO UI Questions:
What information do people want about their surroundings?
When do they want it?
How do they trigger getting that information?

Scenario:
We will test different versions of selecting items. One version is to automatically trigger the information to surface when hovering the reticle over an item for a very short amount of time. The other version will display a "focus” state when hovering the reticle over an item, then allow the user to manually trigger the information by "clicking” on a mouse. 

Test and observe:
- We might want to construct a test similar to A/B testing. Don't test two versions on the same people. 
- We want to find out how fast they are able to collect the information provided to them.
- How many times does a user toggle back and forth between several items.
- How long does a user stay on a single object in both scenarios?

Possible directions during test:
- Example: which two objects will you need to restock on next? (potential spazz advantage)
- Example: find the wasabi (or any small object). (potential click advantage)

Questions to ask after test procedure:
- Was the information provided to you the information you wanted?
- Would the information provided to you about each product enhance your experience at home? Would you want this in your fridge?
- What other information do you want to see about objects in your fridge?

**Comment by FreakTheMighty** [comment]
Lets put this on hold. Closing this for the time being.
